import type { Metadata } from 'next'
import './globals.css'
import DappKitProviders from '@/components/dapp-kit-providers'
import Header from '@/components/header'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Sui Resource Manage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <DappKitProviders>
            <Header />
            {children}
            <Toaster />
          </DappKitProviders>
        </ThemeProvider>
      </body>
    </html>
  )
}
